version: '3'

services:
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
            - ./web/static:/www/static
            - ./web/media:/www/media
        ports:
            - "80:80"

    api:
        build: ./api
        volumes:
            - ./api:/app
            - ./logs/api:/var/log/web
            - ./api/static:/app/static
            - ./api/media:/app/media
        ports:
            - "8000:8000"
        links:
            - postgres:postgres
        env_file:
            - .deploy_env
        command: gunicorn api.wsgi:application -w 4 -b :8000


    postgres:
        image: postgres
        restart: always
        volumes:
            - ./db:/var/lib/postgresql/data/
        ports:
            - "5432:5432"

    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"
