version: '3'

services:
    api:
        build: ./api
        volumes:
            - ./api:/app
        ports:
            - "8000:8000"
        links:
            - postgres:postgres
        env_file:
            - .env
        command: python manage.py runserver 0.0.0.0:8000

    postgres:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./db:/var/lib/postgresql/data/
