version: '3'

services:
    web:
        build: ./web
        volumes:
            - ./web:/app
        ports:
            - "8000:8000"
        links:
            - postgres:postgres
        env_file:
            - .env
        environment:
            DEBUG: 'true'
        command: python manage.py runserver 0.0.0.0:8000

    postgres:
        image: postgres
        ports:
            - "5432:5432"
